spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/management-system-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: public
server:
  port: 8083
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    path: /api-docs
security:
  jwt:
    key:
    exp: 7000000

logging:
  level:
    org.springframework.security: TRACE