spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://system-db:5432/management-system-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: public
server:
  port: 8083
springdoc:
  api-docs:
    path: /api-docs